
version: 2.17
jobs:
  build:
    working_directory: ~/taskapp
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm ci
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: Zip app
          command:  |
            ls
            zip -r taskapp.zip ./
      - run:
          name: Deploy over SSH
          command:  |
            scp taskapp.zip ubuntu@44.200.21.8:~/
            ssh  ubuntu@44.200.21.8 "unzip taskapp.zip";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build