
version: 2.17
jobs:
  build:
    working_directory: ~/taskapp
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh -p your_port_number your_user@your_host "cd ../path/to/your/project; git pull; pm2 start index.js";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build